/**
 *
 */
export default {
  rules: {
    'array-bracket-spacing': [2, 'never'],
    'block-spacing': [2, 'always'],
    'brace-style': [2, 'stroustrup'],
    'camelcase': 1,
    'comma-spacing': [2, { before: false, after: true }],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': [2, 'that'],
    'eol-last': 2,
    'func-names': 0,
    'func-style': [2, 'declaration', { allowArrowFunctions: true }],
    'id-blacklist': 0,
    'id-length': 0,
    'id-match': 0,
    'indent': [2, 2, {
      VariableDeclarator: { var: 2, let: 2, const: 3 },
      SwitchCase: 1,
    }],
    'jsx-quotes': [2, 'prefer-double'],
    'key-spacing': 2,
    'keyword-spacing': 2,
    'linebreak-style': 2,
    'lines-around-comment': [2, {
      beforeBlockComment: true,
      beforeLineComment: true,
      allowBlockStart: true,
      allowBlockEnd: true,
      allowObjectStart: true,
      allowObjectEnd: true,
      allowArrayStart: true,
      allowArrayEnd: true,
    }],
    'max-depth': [2, 5],
    'max-len': [2, 100, 2, {
      ignoreComments: true,
      ignoreUrls: true,
    }],
    'max-nested-callbacks': [2, 3],
    'max-params': [2, 3],
    'max-statements': [2, 10, { ignoreTopLevelFunctions: true }],
    'new-cap': [2, { capIsNew: false, newIsCap: true }],
    'new-parens': 2,
    'newline-after-var': [2, 'always'],
    'newline-per-chained-call': [2, { ignoreChainWithDepth: 3 }],
    'no-array-constructor': 2,
    'no-bitwise': 2,
    'no-continue': 2,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multiple-empty-lines': [2, { max: 2, maxBOF: 0, maxEOF: 1 }],
    'no-negated-condition': 2,
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-plusplus': [2, { allowForLoopAfterthoughts: true }],
    'no-restricted-syntax': 0,
    'no-spaced-func': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': 2,
    'no-whitespace-before-property': 2,
    'object-curly-spacing': [2, 'always', {
      objectsInObjects: true,
      arraysInObjects: true,
    }],
    'one-var': [2, 'never'],
    'one-var-declaration-per-line': [2, 'always'],
    'operator-assignment': [2, 'always'],
    'operator-linebreak': [2, 'before'],
    'padded-blocks': [2, 'never'],
    'quote-props': [2, 'consistent-as-needed'],
    'quotes': [2, 'single', 'avoid-escape'],
    'require-jsdoc': 0,
    'semi': [2, 'never'],
    'semi-spacing': [2, { before: false, after: true }],
    'sort-imports': 0,
    'sort-vars': 0,
    'space-before-blocks': [2, 'always'],
    'space-before-function-paren': [2, 'never'],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'space-unary-ops': [2, { words: true, nonwords: false }],
    'spaced-comment': [2, 'always', { exceptions: ['-', '*']}],
    'wrap-regex': 2,
  },
}
